// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: pb/txn.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Txn_Dir int32

const (
	Txn_FORWARD Txn_Dir = 0
	Txn_REVERSE Txn_Dir = 1
)

// Enum value maps for Txn_Dir.
var (
	Txn_Dir_name = map[int32]string{
		0: "FORWARD",
		1: "REVERSE",
	}
	Txn_Dir_value = map[string]int32{
		"FORWARD": 0,
		"REVERSE": 1,
	}
)

func (x Txn_Dir) Enum() *Txn_Dir {
	p := new(Txn_Dir)
	*p = x
	return p
}

func (x Txn_Dir) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Txn_Dir) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_txn_proto_enumTypes[0].Descriptor()
}

func (Txn_Dir) Type() protoreflect.EnumType {
	return &file_pb_txn_proto_enumTypes[0]
}

func (x Txn_Dir) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Txn_Dir.Descriptor instead.
func (Txn_Dir) EnumDescriptor() ([]byte, []int) {
	return file_pb_txn_proto_rawDescGZIP(), []int{0, 0}
}

type Txn_Step_Status int32

const (
	Txn_Step_PENDING     Txn_Step_Status = 0
	Txn_Step_COMPLETE    Txn_Step_Status = 1
	Txn_Step_ROLLED_BACK Txn_Step_Status = 2
	Txn_Step_ERROR       Txn_Step_Status = 3
)

// Enum value maps for Txn_Step_Status.
var (
	Txn_Step_Status_name = map[int32]string{
		0: "PENDING",
		1: "COMPLETE",
		2: "ROLLED_BACK",
		3: "ERROR",
	}
	Txn_Step_Status_value = map[string]int32{
		"PENDING":     0,
		"COMPLETE":    1,
		"ROLLED_BACK": 2,
		"ERROR":       3,
	}
)

func (x Txn_Step_Status) Enum() *Txn_Step_Status {
	p := new(Txn_Step_Status)
	*p = x
	return p
}

func (x Txn_Step_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Txn_Step_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_txn_proto_enumTypes[1].Descriptor()
}

func (Txn_Step_Status) Type() protoreflect.EnumType {
	return &file_pb_txn_proto_enumTypes[1]
}

func (x Txn_Step_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Txn_Step_Status.Descriptor instead.
func (Txn_Step_Status) EnumDescriptor() ([]byte, []int) {
	return file_pb_txn_proto_rawDescGZIP(), []int{0, 0, 0}
}

type Txn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Direction   Txn_Dir     `protobuf:"varint,1,opt,name=direction,proto3,enum=gaeneco.proto.Txn_Dir" json:"direction,omitempty"`
	CurrentStep int32       `protobuf:"varint,2,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	CanRollback bool        `protobuf:"varint,3,opt,name=can_rollback,json=canRollback,proto3" json:"can_rollback,omitempty"`
	Steps       []*Txn_Step `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
}

func (x *Txn) Reset() {
	*x = Txn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_txn_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Txn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Txn) ProtoMessage() {}

func (x *Txn) ProtoReflect() protoreflect.Message {
	mi := &file_pb_txn_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Txn.ProtoReflect.Descriptor instead.
func (*Txn) Descriptor() ([]byte, []int) {
	return file_pb_txn_proto_rawDescGZIP(), []int{0}
}

func (x *Txn) GetDirection() Txn_Dir {
	if x != nil {
		return x.Direction
	}
	return Txn_FORWARD
}

func (x *Txn) GetCurrentStep() int32 {
	if x != nil {
		return x.CurrentStep
	}
	return 0
}

func (x *Txn) GetCanRollback() bool {
	if x != nil {
		return x.CanRollback
	}
	return false
}

func (x *Txn) GetSteps() []*Txn_Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

type Txn_Step struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model         string               `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Command       string               `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Params        []string             `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	Status        Txn_Step_Status      `protobuf:"varint,4,opt,name=status,proto3,enum=gaeneco.proto.Txn_Step_Status" json:"status,omitempty"`
	MsgId         *Txn_Step_MsgId      `protobuf:"bytes,5,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	ProcessedTime *timestamp.Timestamp `protobuf:"bytes,6,opt,name=processed_time,json=processedTime,proto3" json:"processed_time,omitempty"`
	EffectiveTime *timestamp.Timestamp `protobuf:"bytes,7,opt,name=effective_time,json=effectiveTime,proto3" json:"effective_time,omitempty"`
	Errors        []string             `protobuf:"bytes,8,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *Txn_Step) Reset() {
	*x = Txn_Step{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_txn_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Txn_Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Txn_Step) ProtoMessage() {}

func (x *Txn_Step) ProtoReflect() protoreflect.Message {
	mi := &file_pb_txn_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Txn_Step.ProtoReflect.Descriptor instead.
func (*Txn_Step) Descriptor() ([]byte, []int) {
	return file_pb_txn_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Txn_Step) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Txn_Step) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Txn_Step) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Txn_Step) GetStatus() Txn_Step_Status {
	if x != nil {
		return x.Status
	}
	return Txn_Step_PENDING
}

func (x *Txn_Step) GetMsgId() *Txn_Step_MsgId {
	if x != nil {
		return x.MsgId
	}
	return nil
}

func (x *Txn_Step) GetProcessedTime() *timestamp.Timestamp {
	if x != nil {
		return x.ProcessedTime
	}
	return nil
}

func (x *Txn_Step) GetEffectiveTime() *timestamp.Timestamp {
	if x != nil {
		return x.EffectiveTime
	}
	return nil
}

func (x *Txn_Step) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type Txn_Step_MsgId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Partition int32 `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset    int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *Txn_Step_MsgId) Reset() {
	*x = Txn_Step_MsgId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_txn_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Txn_Step_MsgId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Txn_Step_MsgId) ProtoMessage() {}

func (x *Txn_Step_MsgId) ProtoReflect() protoreflect.Message {
	mi := &file_pb_txn_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Txn_Step_MsgId.ProtoReflect.Descriptor instead.
func (*Txn_Step_MsgId) Descriptor() ([]byte, []int) {
	return file_pb_txn_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Txn_Step_MsgId) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *Txn_Step_MsgId) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_pb_txn_proto protoreflect.FileDescriptor

var file_pb_txn_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x62, 0x2f, 0x74, 0x78, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x67, 0x61, 0x65, 0x6e, 0x65, 0x63, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xae,
	0x05, 0x0a, 0x03, 0x54, 0x78, 0x6e, 0x12, 0x34, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x67, 0x61, 0x65, 0x6e,
	0x65, 0x63, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x78, 0x6e, 0x2e, 0x44, 0x69,
	0x72, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x65, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x65, 0x70, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x61, 0x6e, 0x5f, 0x72, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x63, 0x61, 0x6e, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x12, 0x2d, 0x0a, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x67, 0x61, 0x65, 0x6e, 0x65, 0x63, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x54, 0x78, 0x6e, 0x2e, 0x53, 0x74, 0x65, 0x70, 0x52, 0x05, 0x73, 0x74, 0x65, 0x70,
	0x73, 0x1a, 0xda, 0x03, 0x0a, 0x04, 0x53, 0x74, 0x65, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x12, 0x36, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x67, 0x61, 0x65, 0x6e, 0x65, 0x63, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x54, 0x78, 0x6e, 0x2e, 0x53, 0x74, 0x65, 0x70, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x34, 0x0a, 0x06, 0x6d, 0x73,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x67, 0x61, 0x65,
	0x6e, 0x65, 0x63, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x78, 0x6e, 0x2e, 0x53,
	0x74, 0x65, 0x70, 0x2e, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64,
	0x12, 0x41, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x1a, 0x3d,
	0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x74, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x61, 0x72, 0x74,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x3f, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x4e, 0x44, 0x49,
	0x4e, 0x47, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45,
	0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x4f, 0x4c, 0x4c, 0x45, 0x44, 0x5f, 0x42, 0x41, 0x43,
	0x4b, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x22, 0x1f,
	0x0a, 0x03, 0x44, 0x69, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x4f, 0x52, 0x57, 0x41, 0x52, 0x44,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45, 0x56, 0x45, 0x52, 0x53, 0x45, 0x10, 0x01, 0x42,
	0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x61,
	0x63, 0x68, 0x6c, 0x61, 0x6e, 0x6f, 0x72, 0x72, 0x2f, 0x67, 0x61, 0x65, 0x6e, 0x65, 0x63, 0x6f,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_txn_proto_rawDescOnce sync.Once
	file_pb_txn_proto_rawDescData = file_pb_txn_proto_rawDesc
)

func file_pb_txn_proto_rawDescGZIP() []byte {
	file_pb_txn_proto_rawDescOnce.Do(func() {
		file_pb_txn_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_txn_proto_rawDescData)
	})
	return file_pb_txn_proto_rawDescData
}

var file_pb_txn_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pb_txn_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_txn_proto_goTypes = []interface{}{
	(Txn_Dir)(0),                // 0: gaeneco.proto.Txn.Dir
	(Txn_Step_Status)(0),        // 1: gaeneco.proto.Txn.Step.Status
	(*Txn)(nil),                 // 2: gaeneco.proto.Txn
	(*Txn_Step)(nil),            // 3: gaeneco.proto.Txn.Step
	(*Txn_Step_MsgId)(nil),      // 4: gaeneco.proto.Txn.Step.MsgId
	(*timestamp.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_pb_txn_proto_depIdxs = []int32{
	0, // 0: gaeneco.proto.Txn.direction:type_name -> gaeneco.proto.Txn.Dir
	3, // 1: gaeneco.proto.Txn.steps:type_name -> gaeneco.proto.Txn.Step
	1, // 2: gaeneco.proto.Txn.Step.status:type_name -> gaeneco.proto.Txn.Step.Status
	4, // 3: gaeneco.proto.Txn.Step.msg_id:type_name -> gaeneco.proto.Txn.Step.MsgId
	5, // 4: gaeneco.proto.Txn.Step.processed_time:type_name -> google.protobuf.Timestamp
	5, // 5: gaeneco.proto.Txn.Step.effective_time:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pb_txn_proto_init() }
func file_pb_txn_proto_init() {
	if File_pb_txn_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_txn_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Txn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_txn_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Txn_Step); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_txn_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Txn_Step_MsgId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_txn_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_txn_proto_goTypes,
		DependencyIndexes: file_pb_txn_proto_depIdxs,
		EnumInfos:         file_pb_txn_proto_enumTypes,
		MessageInfos:      file_pb_txn_proto_msgTypes,
	}.Build()
	File_pb_txn_proto = out.File
	file_pb_txn_proto_rawDesc = nil
	file_pb_txn_proto_goTypes = nil
	file_pb_txn_proto_depIdxs = nil
}
