// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: relationships.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerRelatedConcerns struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Characters []*Character `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
}

func (x *PlayerRelatedConcerns) Reset() {
	*x = PlayerRelatedConcerns{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relationships_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerRelatedConcerns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRelatedConcerns) ProtoMessage() {}

func (x *PlayerRelatedConcerns) ProtoReflect() protoreflect.Message {
	mi := &file_relationships_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRelatedConcerns.ProtoReflect.Descriptor instead.
func (*PlayerRelatedConcerns) Descriptor() ([]byte, []int) {
	return file_relationships_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerRelatedConcerns) GetCharacters() []*Character {
	if x != nil {
		return x.Characters
	}
	return nil
}

type PlayerRelatedConfigs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit *Limits `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *PlayerRelatedConfigs) Reset() {
	*x = PlayerRelatedConfigs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relationships_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerRelatedConfigs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRelatedConfigs) ProtoMessage() {}

func (x *PlayerRelatedConfigs) ProtoReflect() protoreflect.Message {
	mi := &file_relationships_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRelatedConfigs.ProtoReflect.Descriptor instead.
func (*PlayerRelatedConfigs) Descriptor() ([]byte, []int) {
	return file_relationships_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerRelatedConfigs) GetLimit() *Limits {
	if x != nil {
		return x.Limit
	}
	return nil
}

type CharacterRelatedConcerns struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player *Player `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *CharacterRelatedConcerns) Reset() {
	*x = CharacterRelatedConcerns{}
	if protoimpl.UnsafeEnabled {
		mi := &file_relationships_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacterRelatedConcerns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterRelatedConcerns) ProtoMessage() {}

func (x *CharacterRelatedConcerns) ProtoReflect() protoreflect.Message {
	mi := &file_relationships_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterRelatedConcerns.ProtoReflect.Descriptor instead.
func (*CharacterRelatedConcerns) Descriptor() ([]byte, []int) {
	return file_relationships_proto_rawDescGZIP(), []int{2}
}

func (x *CharacterRelatedConcerns) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

var File_relationships_proto protoreflect.FileDescriptor

var file_relationships_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a, 0x15, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x6e, 0x63, 0x65, 0x72, 0x6e,
	0x73, 0x12, 0x2d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x73,
	0x22, 0x38, 0x0a, 0x14, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x65,
	0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x12, 0x20, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x73, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x3e, 0x0a, 0x18, 0x43, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x65, 0x64, 0x43, 0x6f,
	0x6e, 0x63, 0x65, 0x72, 0x6e, 0x73, 0x12, 0x22, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x61, 0x63, 0x68, 0x6c, 0x61, 0x6e,
	0x6f, 0x72, 0x72, 0x2f, 0x72, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x2f,
	0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x72, 0x70, 0x67, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_relationships_proto_rawDescOnce sync.Once
	file_relationships_proto_rawDescData = file_relationships_proto_rawDesc
)

func file_relationships_proto_rawDescGZIP() []byte {
	file_relationships_proto_rawDescOnce.Do(func() {
		file_relationships_proto_rawDescData = protoimpl.X.CompressGZIP(file_relationships_proto_rawDescData)
	})
	return file_relationships_proto_rawDescData
}

var file_relationships_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_relationships_proto_goTypes = []interface{}{
	(*PlayerRelatedConcerns)(nil),    // 0: pb.PlayerRelatedConcerns
	(*PlayerRelatedConfigs)(nil),     // 1: pb.PlayerRelatedConfigs
	(*CharacterRelatedConcerns)(nil), // 2: pb.CharacterRelatedConcerns
	(*Character)(nil),                // 3: pb.Character
	(*Limits)(nil),                   // 4: pb.Limits
	(*Player)(nil),                   // 5: pb.Player
}
var file_relationships_proto_depIdxs = []int32{
	3, // 0: pb.PlayerRelatedConcerns.characters:type_name -> pb.Character
	4, // 1: pb.PlayerRelatedConfigs.limit:type_name -> pb.Limits
	5, // 2: pb.CharacterRelatedConcerns.player:type_name -> pb.Player
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_relationships_proto_init() }
func file_relationships_proto_init() {
	if File_relationships_proto != nil {
		return
	}
	file_player_proto_init()
	file_character_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_relationships_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerRelatedConcerns); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relationships_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerRelatedConfigs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_relationships_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharacterRelatedConcerns); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_relationships_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relationships_proto_goTypes,
		DependencyIndexes: file_relationships_proto_depIdxs,
		MessageInfos:      file_relationships_proto_msgTypes,
	}.Build()
	File_relationships_proto = out.File
	file_relationships_proto_rawDesc = nil
	file_relationships_proto_goTypes = nil
	file_relationships_proto_depIdxs = nil
}
